import * as func from './data17.10.js';


console.log('---1---');
console.log(func.squareNumber(3));
console.log(func.squareNumber(1.1));
console.log(func.squareNumber(0));
console.log('---2---');
console.log(func.isSquare(9, 3));
console.log(func.isSquare(0, 0));
console.log(func.isSquare(25, 3));
console.log('---3---');
console.log(func.minimumNumber(9, 3, 2));
console.log(func.minimumNumber(0, 3, 1));
console.log(func.minimumNumber(2, 2, 3));
console.log('---4---');
console.log(func.maximumNumber(9, 3));
console.log(func.maximumNumber(0, 3));
console.log(func.maximumNumber(2, 2));
console.log('---5---');
console.log(func.sequenceGenerator(3));
console.log(func.sequenceGenerator(1));
console.log(func.sequenceGenerator(0));
console.log('---6---');
console.log(func.evenNumbers(4));
console.log(func.evenNumbers(5));
console.log(func.evenNumbers(11));
console.log('---7---');
console.log(func.lastDigit(124));
console.log(func.lastDigit(-532));
console.log(func.lastDigit(123));
console.log('---8---');
console.log(func.secondDigit(124));
console.log(func.secondDigit(-532));
console.log(func.secondDigit(11));
console.log('---9---');
console.log(func.maximumDigit(23));
console.log(func.maximumDigit(21));
console.log(func.maximumDigit(11));
console.log(func.maximumDigit(3));
console.log(func.maximumDigit(121));
console.log('--10---');
console.log(func.removeDigit(208));
console.log(func.removeDigit(109));
console.log(func.removeDigit(940));
console.log('--11---');
console.log(func.divisibleNumber(12, 4));
console.log(func.divisibleNumber(11, 3));
console.log(func.divisibleNumber(5, 5));
console.log('--12---');
console.log(func.isWeekend(1));
console.log(func.isWeekend(6));
console.log(func.isWeekend(9));
console.log('--13---');
console.log(func.isSquare2(2, 4));
console.log(func.isSquare2(81, 9));
console.log(func.isSquare2(25, 125));
console.log('--14---');
console.log(func.getDistance(5, 0));
console.log(func.getDistance(2, 2));
console.log(func.getDistance(7, 4));
console.log('--15---');
console.log(func.isPalindrome(123));
console.log(func.isPalindrome(12421));
console.log(func.isPalindrome(11));
console.log(func.isPalindrome(2000000002));
console.log(func.isPalindrome(-1));
console.log('--16---');
console.log(func.isNumber(123));
console.log(func.isNumber('2'));
console.log(func.isNumber('foo'));
console.log('--17---');
console.log(func.getAmount(3));
console.log(func.getAmount(2));
console.log(func.getAmount(10));
console.log('--18---');
console.log(func.numberLength(123));
console.log(func.numberLength(3));
console.log(func.numberLength(19283));
console.log('--19---');
console.log(func.flipOver('hello'));
console.log(func.flipOver('swap'));
console.log(func.flipOver('John Doe'));
console.log('--20---');
console.log(func.getWordsCount('Every method declaration'));
console.log(func.getWordsCount('A typical program uses types'));
console.log(func.getWordsCount('The interface it implements'));
console.log('--21---');
console.log(func.getWordsCount2('The members, methods, fields, events, and so on that it contains.'));
console.log(func.getWordsCount2('generates, an error, as, shown, in'));
console.log(func.getWordsCount2('base,,, type can in turn derive, , from,,some..other,.type, in'));
